window.COURSE_UI = {
  "locale": "en-GB",
  "languageName": "English",
  "allLevels": "All",
  "levels": [
    {
      "key": "start",
      "label": "Getting started"
    },
    {
      "key": "beginner",
      "label": "Beginner"
    },
    {
      "key": "basic",
      "label": "Basic"
    },
    {
      "key": "intermediate",
      "label": "Intermediate"
    },
    {
      "key": "advanced",
      "label": "Advanced"
    },
    {
      "key": "professional",
      "label": "Professional"
    },
    {
      "key": "projects",
      "label": "Projects"
    }
  ],
  "progressCount": "{done} of {total} lessons",
  "noLessons": "No lessons found.",
  "action": "Action",
  "actions": {
    "file": "File",
    "insert": "Insert",
    "data": "Data",
    "pageLayout": "Page Layout",
    "review": "Review",
    "formulas": "Formulas",
    "grid": "Cell grid",
    "home": "Home",
    "layout": "Layout",
    "design": "Design",
    "references": "References",
    "mailings": "Mailings",
    "view": "View"
  },
  "scene": {
    "sales": "Sales",
    "orders": "Orders",
    "growth": "Growth",
    "chartAria": "Example column chart",
    "formula": "=SUMIFS(Table[Sales],Table[Status],\"Paid\")",
    "category": "Category",
    "total": "Total",
    "stationery": "Stationery",
    "archive": "Archive",
    "grandTotal": "Grand total",
    "fields": "Fields",
    "product": "Product",
    "region": "Region",
    "appliedSteps": "Applied steps",
    "source": "Source",
    "headers": "Headers",
    "changedTypes": "Changed types",
    "price": "Price",
    "quantity": "Qty",
    "status": "Status",
    "notebook": "Notebook",
    "pen": "Pen",
    "folder": "Folder",
    "paid": "Paid",
    "pending": "Pending",
    "annualReport": "Annual report",
    "contents": "Contents",
    "introduction": "Introduction",
    "results": "Results",
    "conclusions": "Conclusions",
    "fieldsUpdated": "Automatic fields updated",
    "teamNewsletter": "Team newsletter",
    "image": "Picture",
    "figureCaption": "Figure 1 — Featured project",
    "shortInfo": "Short, clear and visually organised information.",
    "month": "Month",
    "september": "Sep.",
    "monthlyReport": "Monthly report",
    "reviewBefore": "This paragraph contains a",
    "trackedChange": "tracked change",
    "reviewAfter": "to review.",
    "clearDocument": "The document should be clear, consistent and accessible.",
    "comment": "Comment",
    "confirmValue": "Confirm this value before publishing.",
    "companyReport": "COMPANY · REPORT",
    "featuredProject": "Featured project",
    "firstColumn": "First column with organised information.",
    "secondColumn": "Second column with the essential details.",
    "page": "Page",
    "materialRequest": "Equipment request",
    "name": "Name",
    "writeHere": "Type here…",
    "department": "Department",
    "chooseOption": "Choose an option",
    "date": "Date",
    "confirmData": "I confirm that the information is correct",
    "objective": "Objective.",
    "documentGoal": "Create a clear, easy-to-read document.",
    "documentAdvice": "Use styles, spacing and headings to guide the reader."
  },
  "visualGuide": "Interactive visual guide",
  "visualGuideHelp": "Click the numbered points to see where to work.",
  "stepByStep": "STEP BY STEP",
  "excelSimulation": "Visual Microsoft Excel simulation",
  "excelWorkbookTitle": "Practice workbook — Excel",
  "wordSimulation": "Visual Microsoft Word simulation",
  "wordDocumentTitle": "Practice document — Word",
  "showNextPoint": "Show the next point",
  "clickHere": "Click here",
  "restartGuide": "Restart the guide",
  "playDemo": "Watch the demonstration",
  "pauseDemo": "Pause",
  "replayDemo": "Replay demonstration",
  "whereToClick": "Where to click",
  "whatToDo": "What to do",
  "expectedResult": "Expected result",
  "expectedResultTemplate": "After this step, “{title}” should be visibly applied or ready for the next step.",
  "finalResultTemplate": "At the end, check that you completed “{title}” and that the file shows the requested result.",
  "interfaceLanguage": "Interface and settings",
  "interfaceLanguageNote": "Follow the menu names in {language} ({locale}). Dates, separators and functions use this region.",
  "demoPlaying": "Demonstration playing",
  "demoPaused": "Demonstration paused",
  "stepLabel": "Step {current} of {total}",
  "exactPath": "Exact path",
  "workspaceArea": "{course} workspace",
  "activateDarkMode": "Turn on dark mode",
  "activateLightMode": "Turn on light mode",
  "darkModeEnabled": "Dark mode is on.",
  "lightModeEnabled": "Light mode is on.",
  "realScreenshot": "Real Microsoft {course} screenshot",
  "referenceInterface": "Reference screenshot; labels may vary by language and version.",
  "enlargeImage": "Enlarge image",
  "microsoftSource": "Source: Microsoft Support",
  "courseComplete": "Course complete",
  "almostComplete": "You are almost finished",
  "completedLessons": "You completed all {total} {course} lessons.",
  "remainingOne": "You still have {remaining} lesson to complete.",
  "remainingMany": "You still have {remaining} lessons to complete.",
  "reviewFromStart": "Review from the beginning",
  "firstIncomplete": "Go to the first incomplete lesson",
  "documentTitle": "{title} — Learn {course}",
  "lessonPosition": "Lesson {current} of {total}",
  "missionKicker": "THIS LESSON’S MISSION",
  "missionHelp": "Complete the exercises directly in {course}. Your ticked boxes are saved on this device.",
  "learningEnd": "By the end of this lesson",
  "doIn": "Do this in {course}",
  "tip": "Tip:",
  "practiceHeading": "Exercise programme",
  "practiceIntroduction": "Move from guided practice to independent work, then finish with a challenge.",
  "practiceProgress": "{done}/{total} complete",
  "guidedExercise": "1 · Guided exercise",
  "independentExercise": "2 · Independent exercise",
  "independentIntro": "Repeat the skill without copying the steps. Use the guide only if you get stuck.",
  "independentTask1": "Recreate the result of “{title}” with a different example.",
  "independentTask2": "Use a new {course} file and give it a clear name.",
  "independentTask3": "Compare your result with the visual example and correct any differences.",
  "challenge": "3 · Challenge",
  "challengeIntro": "Apply what you learned to a small real-world work situation.",
  "challengeTask1": "Adapt “{title}” to data or text that you created.",
  "challengeTask2": "Include at least one presentation improvement that makes the result easier to read.",
  "challengeTask3": "Save a final version that is ready to share and check that everything works.",
  "moduleProject": "4 · Module project",
  "projectIntro": "Combine the “{module}” module skills into one complete, useful result.",
  "projectTask1": "Use these skills: {lessons}.",
  "projectTask2": "Create a professional result related to “{module}”.",
  "projectTask3": "Review, test and save the final project in {course}.",
  "verifyLearning": "Check what you learned",
  "checkAnswer": "Check answer",
  "lessonComplete": "Lesson complete.",
  "seeSummary": "See the summary below.",
  "canContinue": "You can continue to the next lesson.",
  "chooseAnswer": "Choose an answer before checking.",
  "correct": "Correct.",
  "notYet": "Not yet.",
  "reviewTryAgain": "Review the steps and try again.",
  "lessonCompleteToast": "Lesson complete — well done!",
  "practiceComplete": "Exercise programme complete. Now answer the question.",
  "resetConfirm": "Do you want to erase the saved progress for this course?",
  "progressReset": "Progress reset."
};
