window.COURSE_UI = {
  locale: 'pt-PT',
  languageName: 'Português de Portugal',
  allLevels: 'Todos',
  levels: [
    { key: 'start', label: 'Iniciação' },
    { key: 'beginner', label: 'Principiante' },
    { key: 'basic', label: 'Básico' },
    { key: 'intermediate', label: 'Intermédio' },
    { key: 'advanced', label: 'Avançado' },
    { key: 'professional', label: 'Profissional' },
    { key: 'projects', label: 'Projetos' }
  ],
  progressCount: '{done} de {total} lições',
  noLessons: 'Nenhuma lição encontrada.',
  action: 'Ação',
  actions: {
    file: 'Ficheiro', insert: 'Inserir', data: 'Dados', pageLayout: 'Esquema de Página',
    review: 'Rever', formulas: 'Fórmulas', grid: 'Grelha de células', home: 'Base',
    layout: 'Esquema', design: 'Estrutura', references: 'Referências',
    mailings: 'Correspondências', view: 'Ver'
  },
  scene: {
    sales: 'Vendas', orders: 'Encomendas', growth: 'Evolução', chartAria: 'Exemplo de gráfico de colunas',
    formula: '=SOMASES(Tabela[Vendas];Tabela[Estado];"Pago")', category: 'Categoria', total: 'Total',
    stationery: 'Papelaria', archive: 'Arquivo', grandTotal: 'Total geral', fields: 'Campos',
    product: 'Produto', region: 'Região', appliedSteps: 'Passos aplicados', source: 'Origem',
    headers: 'Cabeçalhos', changedTypes: 'Tipos alterados', price: 'Preço', quantity: 'Qtd.',
    status: 'Estado', notebook: 'Caderno', pen: 'Caneta', folder: 'Pasta', paid: 'Pago',
    pending: 'Pendente', annualReport: 'Relatório anual', contents: 'Índice', introduction: 'Introdução',
    results: 'Resultados', conclusions: 'Conclusões', fieldsUpdated: 'Campos automáticos atualizados',
    teamNewsletter: 'Boletim da equipa', image: 'Imagem', figureCaption: 'Figura 1 — Projeto em destaque',
    shortInfo: 'Informação curta, clara e organizada visualmente.', month: 'Mês', september: 'Set.',
    monthlyReport: 'Relatório mensal', reviewBefore: 'Este parágrafo contém uma',
    trackedChange: 'alteração acompanhada', reviewAfter: 'para rever.',
    clearDocument: 'O documento deve ser claro, coerente e acessível.', comment: 'Comentário',
    confirmValue: 'Confirme este valor antes de publicar.', companyReport: 'EMPRESA · RELATÓRIO',
    featuredProject: 'Projeto em destaque', firstColumn: 'Primeira coluna com informação organizada.',
    secondColumn: 'Segunda coluna com os detalhes essenciais.', page: 'Página',
    materialRequest: 'Pedido de material', name: 'Nome', writeHere: 'Escreva aqui…',
    department: 'Departamento', chooseOption: 'Escolha uma opção', date: 'Data',
    confirmData: 'Confirmo que os dados estão corretos', objective: 'Objetivo.',
    documentGoal: 'Criar um documento claro e fácil de ler.',
    documentAdvice: 'Use estilos, espaços e títulos para orientar o leitor.'
  },
  visualGuide: 'Guia visual interativo',
  visualGuideHelp: 'Clique nos pontos numerados para saber onde atuar.',
  stepByStep: 'PASSO A PASSO',
  excelSimulation: 'Simulação visual do Microsoft Excel',
  excelWorkbookTitle: 'Livro de exercícios — Excel',
  wordSimulation: 'Simulação visual do Microsoft Word',
  wordDocumentTitle: 'Documento de exercícios — Word',
  showNextPoint: 'Mostrar o ponto seguinte',
  clickHere: 'Clique aqui',
  restartGuide: 'Recomeçar o guia',
  playDemo: 'Ver a demonstração',
  pauseDemo: 'Pausar',
  replayDemo: 'Repetir demonstração',
  animationSpeed: 'Ritmo da demonstração',
  slowSpeed: 'Lento — recomendado',
  normalSpeed: 'Normal',
  whereToClick: 'Onde clicar',
  whatToDo: 'O que fazer',
  expectedResult: 'Resultado esperado',
  expectedResultTemplate: 'Depois deste passo, “{title}” deve ficar visivelmente aplicado ou preparado para o passo seguinte.',
  finalResultTemplate: 'No fim, confirme que concluiu “{title}” e que o ficheiro apresenta o resultado pedido.',
  interfaceLanguage: 'Interface e definições',
  interfaceLanguageNote: 'Siga os nomes dos menus em {language} ({locale}). As datas, os separadores e as funções respeitam esta região.',
  demoPlaying: 'Demonstração em reprodução',
  demoPaused: 'Demonstração em pausa',
  demoFinished: 'Demonstração concluída — reproduza o passo no seu PC',
  speedChanged: 'Ritmo alterado',
  stepLabel: 'Passo {current} de {total}',
  exactPath: 'Caminho exato',
  workspaceArea: 'Área de trabalho do {course}',
  locateControl: 'Localizar',
  performClick: 'Clicar ou premir',
  verifyChange: 'Confirmar o resultado',
  reproduceNow: 'Reproduza agora no seu PC',
  reproduceHelp: 'Pause a demonstração, faça este passo no {course} e compare o seu ecrã com o resultado esperado.',
  markStepDone: 'Marcar como feito no meu PC',
  stepDone: 'Feito no meu PC',
  guideComplete: 'Todos os passos visuais foram reproduzidos no seu PC.',
  keyboardShortcuts: 'Atalhos desta lição',
  keyboardHelp: 'Prima as teclas ligadas por + ao mesmo tempo. As designações abaixo correspondem ao teclado português (Portugal).',
  selectedCell: 'Célula indicada',
  completeNavigation: 'Navegação completa do curso',
  portalHome: 'Todos os cursos',
  switchCourse: 'Mudar entre Excel e Word',
  switchLanguage: 'Escolher língua',
  openExcel: 'Abrir o curso Excel',
  openWord: 'Abrir o curso Word',
  keyboardKeys: {
    ctrl: 'Ctrl', shift: 'Shift', alt: 'Alt', enter: 'Enter', tab: 'Tab', arrow: 'Seta', space: 'Espaço', escape: 'Esc'
  },
  activateDarkMode: 'Ativar modo escuro',
  activateLightMode: 'Ativar modo claro',
  darkModeEnabled: 'Modo escuro ativado.',
  lightModeEnabled: 'Modo claro ativado.',
  realScreenshot: 'Captura real do Microsoft {course}',
  referenceInterface: 'Captura de referência; os rótulos podem variar conforme o idioma e a versão.',
  enlargeImage: 'Ampliar a imagem',
  microsoftSource: 'Fonte: Suporte Microsoft',
  courseComplete: 'Curso concluído',
  almostComplete: 'Está quase a concluir',
  completedLessons: 'Concluiu as {total} lições de {course}.',
  remainingOne: 'Ainda tem {remaining} lição por concluir.',
  remainingMany: 'Ainda tem {remaining} lições por concluir.',
  reviewFromStart: 'Rever desde o início',
  firstIncomplete: 'Ir para a primeira lição por concluir',
  documentTitle: '{title} — Aprender {course}',
  lessonPosition: 'Lição {current} de {total}',
  missionKicker: 'MISSÃO DESTA LIÇÃO',
  missionHelp: 'Faça os exercícios diretamente no {course}. As caixas ficam guardadas neste dispositivo.',
  learningEnd: 'No fim desta lição',
  doIn: 'Faça no {course}',
  tip: 'Dica:',
  practiceHeading: 'Programa de exercícios',
  practiceIntroduction: 'Avance do exercício acompanhado para o trabalho autónomo e termine com um desafio.',
  practiceProgress: '{done}/{total} concluído',
  guidedExercise: '1 · Exercício guiado',
  independentExercise: '2 · Exercício autónomo',
  independentIntro: 'Repita a competência sem copiar os passos. Consulte o guia apenas se ficar bloqueado.',
  independentTask1: 'Recrie o resultado de «{title}» num exemplo diferente.',
  independentTask2: 'Use um ficheiro novo de {course} e dê-lhe um nome claro.',
  independentTask3: 'Compare o seu resultado com o exemplo visual e corrija as diferenças.',
  challenge: '3 · Desafio',
  challengeIntro: 'Aplique o que aprendeu numa pequena situação de trabalho real.',
  challengeTask1: 'Adapte «{title}» a dados ou texto criados por si.',
  challengeTask2: 'Inclua pelo menos uma melhoria de apresentação que facilite a leitura.',
  challengeTask3: 'Guarde uma versão final pronta a partilhar e confirme se tudo funciona.',
  moduleProject: '4 · Projeto do módulo',
  projectIntro: 'Combine as competências do módulo «{module}» num resultado útil e completo.',
  projectTask1: 'Integre estas competências: {lessons}.',
  projectTask2: 'Crie um resultado profissional relacionado com «{module}».',
  projectTask3: 'Revise, teste e guarde o projeto final em {course}.',
  verifyLearning: 'Verifique o que aprendeu',
  checkAnswer: 'Verificar resposta',
  lessonComplete: 'Lição concluída.',
  seeSummary: 'Consulte o resumo abaixo.',
  canContinue: 'Pode avançar para a seguinte.',
  chooseAnswer: 'Escolha uma resposta antes de verificar.',
  correct: 'Correto.',
  notYet: 'Ainda não.',
  reviewTryAgain: 'Reveja os passos e tente novamente.',
  lessonCompleteToast: 'Lição concluída — muito bem!',
  practiceComplete: 'Programa de exercícios concluído. Agora responda à pergunta.',
  resetConfirm: 'Pretende apagar o progresso guardado neste curso?',
  progressReset: 'Progresso reiniciado.'
};
