window.COURSE_UI = {
  "locale": "es-ES",
  "languageName": "Español",
  "allLevels": "Todos",
  "levels": [
    {
      "key": "start",
      "label": "Iniciación"
    },
    {
      "key": "beginner",
      "label": "Principiante"
    },
    {
      "key": "basic",
      "label": "Básico"
    },
    {
      "key": "intermediate",
      "label": "Intermedio"
    },
    {
      "key": "advanced",
      "label": "Avanzado"
    },
    {
      "key": "professional",
      "label": "Profesional"
    },
    {
      "key": "projects",
      "label": "Proyectos"
    }
  ],
  "progressCount": "{done} de {total} lecciones",
  "noLessons": "No se encontró ninguna lección.",
  "action": "Acción",
  "actions": {
    "file": "Archivo",
    "insert": "Insertar",
    "data": "Datos",
    "pageLayout": "Diseño de página",
    "review": "Revisar",
    "formulas": "Fórmulas",
    "grid": "Cuadrícula de celdas",
    "home": "Inicio",
    "layout": "Disposición",
    "design": "Diseño",
    "references": "Referencias",
    "mailings": "Correspondencia",
    "view": "Vista"
  },
  "scene": {
    "sales": "Ventas",
    "orders": "Pedidos",
    "growth": "Evolución",
    "chartAria": "Ejemplo de gráfico de columnas",
    "formula": "=SUMAR.SI.CONJUNTO(Tabla[Ventas];Tabla[Estado];\"Pagado\")",
    "category": "Categoría",
    "total": "Total",
    "stationery": "Papelería",
    "archive": "Archivo",
    "grandTotal": "Total general",
    "fields": "Campos",
    "product": "Producto",
    "region": "Región",
    "appliedSteps": "Pasos aplicados",
    "source": "Origen",
    "headers": "Encabezados",
    "changedTypes": "Tipos cambiados",
    "price": "Precio",
    "quantity": "Cant.",
    "status": "Estado",
    "notebook": "Cuaderno",
    "pen": "Bolígrafo",
    "folder": "Carpeta",
    "paid": "Pagado",
    "pending": "Pendiente",
    "annualReport": "Informe anual",
    "contents": "Tabla de contenido",
    "introduction": "Introducción",
    "results": "Resultados",
    "conclusions": "Conclusiones",
    "fieldsUpdated": "Campos automáticos actualizados",
    "teamNewsletter": "Boletín del equipo",
    "image": "Imagen",
    "figureCaption": "Figura 1 — Proyecto destacado",
    "shortInfo": "Información breve, clara y organizada visualmente.",
    "month": "Mes",
    "september": "Sept.",
    "monthlyReport": "Informe mensual",
    "reviewBefore": "Este párrafo contiene un",
    "trackedChange": "cambio controlado",
    "reviewAfter": "para revisar.",
    "clearDocument": "El documento debe ser claro, coherente y accesible.",
    "comment": "Comentario",
    "confirmValue": "Confirma este valor antes de publicar.",
    "companyReport": "EMPRESA · INFORME",
    "featuredProject": "Proyecto destacado",
    "firstColumn": "Primera columna con información organizada.",
    "secondColumn": "Segunda columna con los detalles esenciales.",
    "page": "Página",
    "materialRequest": "Solicitud de material",
    "name": "Nombre",
    "writeHere": "Escribe aquí…",
    "department": "Departamento",
    "chooseOption": "Elige una opción",
    "date": "Fecha",
    "confirmData": "Confirmo que los datos son correctos",
    "objective": "Objetivo.",
    "documentGoal": "Crear un documento claro y fácil de leer.",
    "documentAdvice": "Utiliza estilos, espacios y títulos para guiar al lector."
  },
  "visualGuide": "Guía visual interactiva",
  "visualGuideHelp": "Haz clic en los puntos numerados para saber dónde actuar.",
  "stepByStep": "PASO A PASO",
  "excelSimulation": "Simulación visual de Microsoft Excel",
  "excelWorkbookTitle": "Libro de ejercicios — Excel",
  "wordSimulation": "Simulación visual de Microsoft Word",
  "wordDocumentTitle": "Documento de ejercicios — Word",
  "showNextPoint": "Mostrar el punto siguiente",
  "clickHere": "Haz clic aquí",
  "restartGuide": "Reiniciar la guía",
  "activateDarkMode": "Activar el modo oscuro",
  "activateLightMode": "Activar el modo claro",
  "darkModeEnabled": "Modo oscuro activado.",
  "lightModeEnabled": "Modo claro activado.",
  "realScreenshot": "Captura real de Microsoft {course}",
  "referenceInterface": "Captura de referencia; las etiquetas pueden variar según el idioma y la versión.",
  "enlargeImage": "Ampliar la imagen",
  "microsoftSource": "Fuente: Soporte de Microsoft",
  "courseComplete": "Curso completado",
  "almostComplete": "Ya casi has terminado",
  "completedLessons": "Has completado las {total} lecciones de {course}.",
  "remainingOne": "Aún queda {remaining} lección por completar.",
  "remainingMany": "Aún quedan {remaining} lecciones por completar.",
  "reviewFromStart": "Repasar desde el principio",
  "firstIncomplete": "Ir a la primera lección sin completar",
  "documentTitle": "{title} — Aprender {course}",
  "lessonPosition": "Lección {current} de {total}",
  "missionKicker": "MISIÓN DE ESTA LECCIÓN",
  "missionHelp": "Realiza los ejercicios directamente en {course}. Las casillas se guardan en este dispositivo.",
  "learningEnd": "Al final de esta lección",
  "doIn": "Hazlo en {course}",
  "tip": "Consejo:",
  "practiceHeading": "Programa de ejercicios",
  "practiceIntroduction": "Pasa del ejercicio guiado al trabajo autónomo y termina con un reto.",
  "practiceProgress": "{done}/{total} completado",
  "guidedExercise": "1 · Ejercicio guiado",
  "independentExercise": "2 · Ejercicio autónomo",
  "independentIntro": "Repite la habilidad sin copiar los pasos. Consulta la guía solo si te bloqueas.",
  "independentTask1": "Recrea el resultado de «{title}» con un ejemplo diferente.",
  "independentTask2": "Utiliza un archivo nuevo de {course} y ponle un nombre claro.",
  "independentTask3": "Compara tu resultado con el ejemplo visual y corrige las diferencias.",
  "challenge": "3 · Reto",
  "challengeIntro": "Aplica lo aprendido a una pequeña situación de trabajo real.",
  "challengeTask1": "Adapta «{title}» a datos o texto creados por ti.",
  "challengeTask2": "Incluye al menos una mejora de presentación que facilite la lectura.",
  "challengeTask3": "Guarda una versión final lista para compartir y comprueba que todo funciona.",
  "moduleProject": "4 · Proyecto del módulo",
  "projectIntro": "Combina las habilidades del módulo «{module}» en un resultado útil y completo.",
  "projectTask1": "Integra estas habilidades: {lessons}.",
  "projectTask2": "Crea un resultado profesional relacionado con «{module}».",
  "projectTask3": "Revisa, prueba y guarda el proyecto final en {course}.",
  "verifyLearning": "Comprueba lo que has aprendido",
  "checkAnswer": "Comprobar respuesta",
  "lessonComplete": "Lección completada.",
  "seeSummary": "Consulta el resumen de abajo.",
  "canContinue": "Puedes avanzar a la siguiente.",
  "chooseAnswer": "Elige una respuesta antes de comprobar.",
  "correct": "Correcto.",
  "notYet": "Todavía no.",
  "reviewTryAgain": "Revisa los pasos e inténtalo de nuevo.",
  "lessonCompleteToast": "Lección completada — ¡muy bien!",
  "practiceComplete": "Programa de ejercicios completado. Ahora responde a la pregunta.",
  "resetConfirm": "¿Quieres borrar el progreso guardado en este curso?",
  "progressReset": "Progreso reiniciado."
};
