window.COURSE_UI = {
  "locale": "fr-FR",
  "languageName": "Français",
  "allLevels": "Tous",
  "levels": [
    {
      "key": "start",
      "label": "Initiation"
    },
    {
      "key": "beginner",
      "label": "Débutant"
    },
    {
      "key": "basic",
      "label": "Basique"
    },
    {
      "key": "intermediate",
      "label": "Intermédiaire"
    },
    {
      "key": "advanced",
      "label": "Avancé"
    },
    {
      "key": "professional",
      "label": "Professionnel"
    },
    {
      "key": "projects",
      "label": "Projets"
    }
  ],
  "progressCount": "{done} sur {total} leçons",
  "noLessons": "Aucune leçon trouvée.",
  "action": "Action",
  "actions": {
    "file": "Fichier",
    "insert": "Insertion",
    "data": "Données",
    "pageLayout": "Mise en page",
    "review": "Révision",
    "formulas": "Formules",
    "grid": "Grille de cellules",
    "home": "Accueil",
    "layout": "Disposition",
    "design": "Création",
    "references": "Références",
    "mailings": "Publipostage",
    "view": "Affichage"
  },
  "scene": {
    "sales": "Ventes",
    "orders": "Commandes",
    "growth": "Évolution",
    "chartAria": "Exemple de graphique en colonnes",
    "formula": "=SOMME.SI.ENS(Tableau[Ventes];Tableau[État];\"Payé\")",
    "category": "Catégorie",
    "total": "Total",
    "stationery": "Papeterie",
    "archive": "Archives",
    "grandTotal": "Total général",
    "fields": "Champs",
    "product": "Produit",
    "region": "Région",
    "appliedSteps": "Étapes appliquées",
    "source": "Source",
    "headers": "En-têtes",
    "changedTypes": "Types modifiés",
    "price": "Prix",
    "quantity": "Qté",
    "status": "État",
    "notebook": "Cahier",
    "pen": "Stylo",
    "folder": "Dossier",
    "paid": "Payé",
    "pending": "En attente",
    "annualReport": "Rapport annuel",
    "contents": "Table des matières",
    "introduction": "Introduction",
    "results": "Résultats",
    "conclusions": "Conclusions",
    "fieldsUpdated": "Champs automatiques mis à jour",
    "teamNewsletter": "Bulletin de l’équipe",
    "image": "Image",
    "figureCaption": "Figure 1 — Projet à la une",
    "shortInfo": "Information courte, claire et bien organisée.",
    "month": "Mois",
    "september": "Sept.",
    "monthlyReport": "Rapport mensuel",
    "reviewBefore": "Ce paragraphe contient une",
    "trackedChange": "modification suivie",
    "reviewAfter": "à réviser.",
    "clearDocument": "Le document doit être clair, cohérent et accessible.",
    "comment": "Commentaire",
    "confirmValue": "Confirmez cette valeur avant de publier.",
    "companyReport": "ENTREPRISE · RAPPORT",
    "featuredProject": "Projet à la une",
    "firstColumn": "Première colonne avec des informations organisées.",
    "secondColumn": "Deuxième colonne avec les détails essentiels.",
    "page": "Page",
    "materialRequest": "Demande de matériel",
    "name": "Nom",
    "writeHere": "Écrivez ici…",
    "department": "Service",
    "chooseOption": "Choisissez une option",
    "date": "Date",
    "confirmData": "Je confirme que les données sont correctes",
    "objective": "Objectif.",
    "documentGoal": "Créer un document clair et facile à lire.",
    "documentAdvice": "Utilisez des styles, des espaces et des titres pour guider le lecteur."
  },
  "visualGuide": "Guide visuel interactif",
  "visualGuideHelp": "Cliquez sur les points numérotés pour savoir où agir.",
  "stepByStep": "ÉTAPE PAR ÉTAPE",
  "excelSimulation": "Simulation visuelle de Microsoft Excel",
  "excelWorkbookTitle": "Classeur d’exercices — Excel",
  "wordSimulation": "Simulation visuelle de Microsoft Word",
  "wordDocumentTitle": "Document d’exercices — Word",
  "showNextPoint": "Afficher le point suivant",
  "clickHere": "Cliquez ici",
  "restartGuide": "Recommencer le guide",
  "playDemo": "Voir la démonstration",
  "pauseDemo": "Mettre en pause",
  "replayDemo": "Revoir la démonstration",
  "animationSpeed": "Rythme de la démonstration",
  "slowSpeed": "Lent — recommandé",
  "normalSpeed": "Normal",
  "whereToClick": "Où cliquer",
  "whatToDo": "Ce qu’il faut faire",
  "expectedResult": "Résultat attendu",
  "expectedResultTemplate": "Après cette étape, « {title} » doit être visiblement appliqué ou prêt pour l’étape suivante.",
  "finalResultTemplate": "À la fin, vérifiez que « {title} » est terminé et que le fichier présente le résultat demandé.",
  "interfaceLanguage": "Interface et paramètres",
  "interfaceLanguageNote": "Suivez les noms des menus en {language} ({locale}). Les dates, séparateurs et fonctions respectent cette région.",
  "demoPlaying": "Démonstration en cours",
  "demoPaused": "Démonstration en pause",
  "demoFinished": "Démonstration terminée — reproduisez l’étape sur votre PC",
  "speedChanged": "Rythme modifié",
  "stepLabel": "Étape {current} sur {total}",
  "exactPath": "Chemin exact",
  "workspaceArea": "Zone de travail de {course}",
  "locateControl": "Repérer",
  "performClick": "Cliquer ou appuyer",
  "verifyChange": "Vérifier le résultat",
  "reproduceNow": "Reproduisez maintenant sur votre PC",
  "reproduceHelp": "Mettez la démonstration en pause, réalisez cette étape dans {course}, puis comparez votre écran au résultat attendu.",
  "markStepDone": "Marquer comme fait sur mon PC",
  "stepDone": "Fait sur mon PC",
  "guideComplete": "Toutes les étapes visuelles ont été reproduites sur votre PC.",
  "keyboardShortcuts": "Raccourcis de cette leçon",
  "keyboardHelp": "Appuyez en même temps sur les touches reliées par +. Les noms ci-dessous correspondent au clavier français.",
  "keyboardKeys": {
    "ctrl": "Ctrl",
    "shift": "Maj",
    "alt": "Alt",
    "enter": "Entrée",
    "tab": "Tabulation",
    "arrow": "Flèche",
    "space": "Espace",
    "escape": "Échap"
  },
  "activateDarkMode": "Activer le mode sombre",
  "activateLightMode": "Activer le mode clair",
  "darkModeEnabled": "Mode sombre activé.",
  "lightModeEnabled": "Mode clair activé.",
  "realScreenshot": "Capture réelle de Microsoft {course}",
  "referenceInterface": "Capture de référence ; les libellés peuvent varier selon la langue et la version.",
  "enlargeImage": "Agrandir l’image",
  "microsoftSource": "Source : Support Microsoft",
  "courseComplete": "Cours terminé",
  "almostComplete": "Vous avez presque terminé",
  "completedLessons": "Vous avez terminé les {total} leçons de {course}.",
  "remainingOne": "Il reste {remaining} leçon à terminer.",
  "remainingMany": "Il reste {remaining} leçons à terminer.",
  "reviewFromStart": "Revoir depuis le début",
  "firstIncomplete": "Aller à la première leçon non terminée",
  "documentTitle": "{title} — Apprendre {course}",
  "lessonPosition": "Leçon {current} sur {total}",
  "missionKicker": "MISSION DE CETTE LEÇON",
  "missionHelp": "Réalisez les exercices directement dans {course}. Les cases restent enregistrées sur cet appareil.",
  "learningEnd": "À la fin de cette leçon",
  "doIn": "À faire dans {course}",
  "tip": "Conseil :",
  "practiceHeading": "Programme d’exercices",
  "practiceIntroduction": "Passez de l’exercice accompagné au travail autonome, puis terminez par un défi.",
  "practiceProgress": "{done}/{total} terminé",
  "guidedExercise": "1 · Exercice guidé",
  "independentExercise": "2 · Exercice autonome",
  "independentIntro": "Répétez la compétence sans copier les étapes. Consultez le guide seulement si vous êtes bloqué.",
  "independentTask1": "Recréez le résultat de « {title} » avec un autre exemple.",
  "independentTask2": "Utilisez un nouveau fichier {course} et donnez-lui un nom clair.",
  "independentTask3": "Comparez votre résultat à l’exemple visuel et corrigez les différences.",
  "challenge": "3 · Défi",
  "challengeIntro": "Appliquez votre apprentissage à une petite situation professionnelle réelle.",
  "challengeTask1": "Adaptez « {title} » à des données ou à un texte que vous avez créés.",
  "challengeTask2": "Ajoutez au moins une amélioration de présentation qui facilite la lecture.",
  "challengeTask3": "Enregistrez une version finale prête à partager et vérifiez que tout fonctionne.",
  "moduleProject": "4 · Projet du module",
  "projectIntro": "Combinez les compétences du module « {module} » dans un résultat utile et complet.",
  "projectTask1": "Intégrez ces compétences : {lessons}.",
  "projectTask2": "Créez un résultat professionnel lié à « {module} ».",
  "projectTask3": "Révisez, testez et enregistrez le projet final dans {course}.",
  "verifyLearning": "Vérifiez ce que vous avez appris",
  "checkAnswer": "Vérifier la réponse",
  "lessonComplete": "Leçon terminée.",
  "seeSummary": "Consultez le résumé ci-dessous.",
  "canContinue": "Vous pouvez passer à la suivante.",
  "chooseAnswer": "Choisissez une réponse avant de vérifier.",
  "correct": "Correct.",
  "notYet": "Pas encore.",
  "reviewTryAgain": "Relisez les étapes et réessayez.",
  "lessonCompleteToast": "Leçon terminée — bravo !",
  "practiceComplete": "Programme d’exercices terminé. Répondez maintenant à la question.",
  "resetConfirm": "Voulez-vous effacer la progression enregistrée pour ce cours ?",
  "progressReset": "Progression réinitialisée."
};
